### ISSUE TITLE
Transform error after minification

### ISSUE THREAD

**Issue by narenst** [filestack/filestack-react#16]
I get this exception when trying to upload a cropped an image. After this error, the upload finishes but the image is not cropped - the original images appears as is.

But I get this error only after going through the react build process (`npm run build`). When running in development mode (i.e., the app is started using `npm start` command) the crop operation works fine. Let me know if there is any other information you need here:

```
react-filestack.js:13 TypeError: a.transform is not a function
    at performTransformations (http://localhost:3000/static/js/main.2292896d.js:81:414)
    at Array.<anonymous> (http://localhost:3000/static/js/main.2292896d.js:76:27183)
    at Gi.e.exports.Gi.dispatch (http://localhost:3000/static/js/main.2292896d.js:77:30797)
    at Gi.dispatch (http://localhost:3000/static/js/main.2292896d.js:77:29839)
    at a.n.(anonymous function) (http://localhost:3000/static/js/main.2292896d.js:78:1120)
    at a.n [as performTransformations] (http://localhost:3000/static/js/main.2292896d.js:75:27609)
    at a.destroyed (http://localhost:3000/static/js/main.2292896d.js:80:5453)
    at de (http://localhost:3000/static/js/main.2292896d.js:76:3437)
    at a.e.exports.e.$destroy (http://localhost:3000/static/js/main.2292896d.js:77:8670)
    at destroy (http://localhost:3000/static/js/main.2292896d.js:77:6282)
F	@	react-filestack.js:13
de	@	react-filestack.js:13
e.exports.e.$destroy	@	react-filestack.js:13
destroy	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
e.exports.e.nodeOps	@	react-filestack.js:13
e.exports.e.$destroy	@	react-filestack.js:13
destroy	@	react-filestack.js:13
y	@	react-filestack.js:13
e.exports.e.nodeOps	@	react-filestack.js:13
e.exports.e.$destroy	@	react-filestack.js:13
destroy	@	react-filestack.js:13
y	@	react-filestack.js:13
y	@	react-filestack.js:13
e.exports.e.nodeOps	@	react-filestack.js:13
e.exports.e.$destroy	@	react-filestack.js:13
destroy	@	react-filestack.js:13
y	@	react-filestack.js:13
e.exports.e.nodeOps	@	react-filestack.js:13
e.exports.e.$destroy	@	react-filestack.js:13
handler	@	react-filestack.js:13
e.exports.po.run	@	react-filestack.js:13
pe	@	react-filestack.js:13
(anonymous)	@	react-filestack.js:13
e	@	react-filestack.js:13
```

**Comment by samuxyz** [comment]
@narenst Sorry for the late reply, have you tried with the latest version of filestack-react?

**Comment by AndrzejSala** [comment]
@narenst It looks like the problem does not appear when using a new version.
